import type { Ability, ClassTrack } from './model';
export interface ClassDefinition {
  id: string;
  name: string;
  hitDie: 6 | 8 | 10 | 12;
  caster: ClassTrack['caster'];
  ability: Ability;
  saves: Ability[];
  prerequisites: Partial<Record<Ability, number>>[];
  skills: number;
  skillOptions: string[];
  subclassLevel: number;
  asi: number[];
  gains: Record<number, string[]>;
}
const allSkills = [
  'Acrobatics',
  'Animal Handling',
  'Arcana',
  'Athletics',
  'Deception',
  'History',
  'Insight',
  'Intimidation',
  'Investigation',
  'Medicine',
  'Nature',
  'Perception',
  'Performance',
  'Persuasion',
  'Religion',
  'Sleight of Hand',
  'Stealth',
  'Survival',
];
const make = (
  id: string,
  name: string,
  hitDie: 6 | 8 | 10 | 12,
  caster: ClassTrack['caster'],
  ability: Ability,
  saves: Ability[],
  prerequisites: ClassDefinition['prerequisites'],
  subclassLevel: number,
  gains: Record<number, string[]>,
  skills = 2,
  skillOptions = allSkills,
  asi = [4, 8, 12, 16, 19],
): ClassDefinition => ({
  id,
  name,
  hitDie,
  caster,
  ability,
  saves,
  prerequisites,
  subclassLevel,
  gains,
  skills,
  skillOptions,
  asi,
});
export const classes: ClassDefinition[] = [
  make(
    'barbarian',
    'Barbarian',
    12,
    'none',
    'str',
    ['str', 'con'],
    [{ str: 13 }],
    3,
    {
      1: ['Rage', 'Unarmored Defense'],
      2: ['Reckless Attack', 'Danger Sense'],
      3: ['Primal Path'],
      5: ['Extra Attack', 'Fast Movement'],
      7: ['Feral Instinct'],
      9: ['Brutal Critical'],
      11: ['Relentless Rage'],
      15: ['Persistent Rage'],
      18: ['Indomitable Might'],
      20: ['Primal Champion'],
    },
    2,
    ['Animal Handling', 'Athletics', 'Intimidation', 'Nature', 'Perception', 'Survival'],
  ),
  make(
    'bard',
    'Bard',
    8,
    'full',
    'cha',
    ['dex', 'cha'],
    [{ cha: 13 }],
    3,
    {
      1: ['Spellcasting', 'Bardic Inspiration'],
      2: ['Jack of All Trades', 'Song of Rest'],
      3: ['Bard College', 'Expertise'],
      5: ['Font of Inspiration'],
      6: ['Countercharm'],
      10: ['Magical Secrets', 'Expertise'],
      14: ['Magical Secrets'],
      18: ['Magical Secrets'],
      20: ['Superior Inspiration'],
    },
    3,
  ),
  make(
    'cleric',
    'Cleric',
    8,
    'full',
    'wis',
    ['wis', 'cha'],
    [{ wis: 13 }],
    1,
    {
      1: ['Spellcasting', 'Divine Domain'],
      2: ['Channel Divinity', 'Turn Undead'],
      5: ['Destroy Undead'],
      10: ['Divine Intervention'],
      20: ['Improved Divine Intervention'],
    },
    2,
    ['History', 'Insight', 'Medicine', 'Persuasion', 'Religion'],
  ),
  make(
    'druid',
    'Druid',
    8,
    'full',
    'wis',
    ['int', 'wis'],
    [{ wis: 13 }],
    2,
    {
      1: ['Druidic', 'Spellcasting'],
      2: ['Wild Shape', 'Druid Circle'],
      18: ['Timeless Body', 'Beast Spells'],
      20: ['Archdruid'],
    },
    2,
    [
      'Arcana',
      'Animal Handling',
      'Insight',
      'Medicine',
      'Nature',
      'Perception',
      'Religion',
      'Survival',
    ],
  ),
  make(
    'fighter',
    'Fighter',
    10,
    'none',
    'str',
    ['str', 'con'],
    [{ str: 13 }, { dex: 13 }],
    3,
    {
      1: ['Fighting Style', 'Second Wind'],
      2: ['Action Surge'],
      3: ['Martial Archetype'],
      5: ['Extra Attack'],
      9: ['Indomitable'],
      11: ['Extra Attack (2)'],
      17: ['Action Surge (2)'],
      20: ['Extra Attack (3)'],
    },
    2,
    [
      'Acrobatics',
      'Animal Handling',
      'Athletics',
      'History',
      'Insight',
      'Intimidation',
      'Perception',
      'Survival',
    ],
    [4, 6, 8, 12, 14, 16, 19],
  ),
  make(
    'monk',
    'Monk',
    8,
    'none',
    'wis',
    ['str', 'dex'],
    [{ dex: 13, wis: 13 }],
    3,
    {
      1: ['Unarmored Defense', 'Martial Arts'],
      2: ['Ki', 'Unarmored Movement'],
      3: ['Monastic Tradition', 'Deflect Missiles'],
      4: ['Slow Fall'],
      5: ['Extra Attack', 'Stunning Strike'],
      6: ['Ki-Empowered Strikes'],
      7: ['Evasion', 'Stillness of Mind'],
      10: ['Purity of Body'],
      13: ['Tongue of the Sun and Moon'],
      14: ['Diamond Soul'],
      15: ['Timeless Body'],
      18: ['Empty Body'],
      20: ['Perfect Self'],
    },
    2,
    ['Acrobatics', 'Athletics', 'History', 'Insight', 'Religion', 'Stealth'],
  ),
  make(
    'paladin',
    'Paladin',
    10,
    'half',
    'cha',
    ['wis', 'cha'],
    [{ str: 13, cha: 13 }],
    3,
    {
      1: ['Divine Sense', 'Lay on Hands'],
      2: ['Fighting Style', 'Spellcasting', 'Divine Smite'],
      3: ['Divine Health', 'Sacred Oath'],
      5: ['Extra Attack'],
      6: ['Aura of Protection'],
      10: ['Aura of Courage'],
      11: ['Improved Divine Smite'],
      14: ['Cleansing Touch'],
    },
    2,
    ['Athletics', 'Insight', 'Intimidation', 'Medicine', 'Persuasion', 'Religion'],
  ),
  make(
    'ranger',
    'Ranger',
    10,
    'half',
    'wis',
    ['str', 'dex'],
    [{ dex: 13, wis: 13 }],
    3,
    {
      1: ['Favored Enemy', 'Natural Explorer'],
      2: ['Fighting Style', 'Spellcasting'],
      3: ['Ranger Archetype', 'Primeval Awareness'],
      5: ['Extra Attack'],
      8: ['Land’s Stride'],
      10: ['Hide in Plain Sight'],
      14: ['Vanish'],
      18: ['Feral Senses'],
      20: ['Foe Slayer'],
    },
    3,
    [
      'Animal Handling',
      'Athletics',
      'Insight',
      'Investigation',
      'Nature',
      'Perception',
      'Stealth',
      'Survival',
    ],
  ),
  make(
    'rogue',
    'Rogue',
    8,
    'none',
    'int',
    ['dex', 'int'],
    [{ dex: 13 }],
    3,
    {
      1: ['Expertise', 'Sneak Attack', 'Thieves’ Cant'],
      2: ['Cunning Action'],
      3: ['Roguish Archetype'],
      5: ['Uncanny Dodge'],
      7: ['Evasion'],
      11: ['Reliable Talent'],
      14: ['Blindsense'],
      15: ['Slippery Mind'],
      18: ['Elusive'],
      20: ['Stroke of Luck'],
    },
    4,
    [
      'Acrobatics',
      'Athletics',
      'Deception',
      'Insight',
      'Intimidation',
      'Investigation',
      'Perception',
      'Performance',
      'Persuasion',
      'Sleight of Hand',
      'Stealth',
    ],
    [4, 8, 10, 12, 16, 19],
  ),
  make(
    'sorcerer',
    'Sorcerer',
    6,
    'full',
    'cha',
    ['con', 'cha'],
    [{ cha: 13 }],
    1,
    {
      1: ['Spellcasting', 'Sorcerous Origin'],
      2: ['Font of Magic'],
      3: ['Metamagic'],
      20: ['Sorcerous Restoration'],
    },
    2,
    ['Arcana', 'Deception', 'Insight', 'Intimidation', 'Persuasion', 'Religion'],
  ),
  make(
    'warlock',
    'Warlock',
    8,
    'pact',
    'cha',
    ['wis', 'cha'],
    [{ cha: 13 }],
    1,
    {
      1: ['Otherworldly Patron', 'Pact Magic'],
      2: ['Eldritch Invocations'],
      3: ['Pact Boon'],
      11: ['Mystic Arcanum (6th)'],
      13: ['Mystic Arcanum (7th)'],
      15: ['Mystic Arcanum (8th)'],
      17: ['Mystic Arcanum (9th)'],
      20: ['Eldritch Master'],
    },
    2,
    ['Arcana', 'Deception', 'History', 'Intimidation', 'Investigation', 'Nature', 'Religion'],
  ),
  make(
    'wizard',
    'Wizard',
    6,
    'full',
    'int',
    ['int', 'wis'],
    [{ int: 13 }],
    2,
    {
      1: ['Spellcasting', 'Arcane Recovery'],
      2: ['Arcane Tradition'],
      18: ['Spell Mastery'],
      20: ['Signature Spells'],
    },
    2,
    ['Arcana', 'History', 'Insight', 'Investigation', 'Medicine', 'Religion'],
  ),
  make(
    'artificer',
    'Artificer',
    8,
    'artificer',
    'int',
    ['con', 'int'],
    [{ int: 13 }],
    3,
    {
      1: ['Magical Tinkering', 'Spellcasting'],
      2: ['Infuse Item'],
      3: ['Artificer Specialist', 'The Right Tool for the Job'],
      6: ['Tool Expertise'],
      7: ['Flash of Genius'],
      10: ['Magic Item Adept'],
      11: ['Spell-Storing Item'],
      14: ['Magic Item Savant'],
      18: ['Magic Item Master'],
      20: ['Soul of Artifice'],
    },
    2,
    ['Arcana', 'History', 'Investigation', 'Medicine', 'Nature', 'Perception', 'Sleight of Hand'],
  ),
];
export const classById = (id: string) => classes.find((c) => c.id === id);
export const slotTable: number[][] = [
  [],
  [2],
  [3],
  [4, 2],
  [4, 3],
  [4, 3, 2],
  [4, 3, 3],
  [4, 3, 3, 1],
  [4, 3, 3, 2],
  [4, 3, 3, 3, 1],
  [4, 3, 3, 3, 2],
  [4, 3, 3, 3, 2, 1],
  [4, 3, 3, 3, 2, 1],
  [4, 3, 3, 3, 2, 1, 1],
  [4, 3, 3, 3, 2, 1, 1],
  [4, 3, 3, 3, 2, 1, 1, 1],
  [4, 3, 3, 3, 2, 1, 1, 1],
  [4, 3, 3, 3, 2, 1, 1, 1, 1],
  [4, 3, 3, 3, 3, 1, 1, 1, 1],
  [4, 3, 3, 3, 3, 2, 1, 1, 1],
  [4, 3, 3, 3, 3, 2, 2, 1, 1],
];
